version: '3'
services:
 mongodb:
   image: mongo:3.3   
   expose:                 
     - "27017"
   volumes:
     - db_data:/data/db
   environment:    
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   #image: teamcloudyuga/rsvpapp:mooc
   build: .
   ports:
    - "5000:5000"
   environment:
    MONGODB_HOST: mongodb
#    LINK: http://www.meetup.com/cloudyuga/
    TEXT1: Flugel 
    TEXT2: Garage Flugel RSVP!
#    LOGO: https://raw.githubusercontent.com/cloudyuga/rsvpapp/master/static/cloudyuga.png
    COMPANY: Flugel Technology Pvt. Ltd.
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
